# Generated by Django 3.2.7 on 2021-09-15 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('saletype', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], default='for_sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nametype', models.CharField(choices=[('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse')], default='house', max_length=50)),
                ('sqft', models.IntegerField()),
                ('openhouse', models.BooleanField(default=False)),
                ('photomain', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo7', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo8', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo9', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo10', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo11', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo12', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo13', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo14', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo15', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo16', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo17', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo18', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo19', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo20', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('ispublished', models.BooleanField(default=True)),
                ('listdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
